# Generated by Django 5.2.7 on 2025-11-09 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/', verbose_name='Изображение'),
        ),
    ]
